
# Java

.PHONY: lint-java test-java check-java
lint: lint-java
test: test-java
check: check-java

lint-java: ## Check the Java sources with PMD, and with javac and javadoc warnings as errors
	./gradlew --init-script gradle/ergon-java.init.gradle.kts check javadoc -x test
test-java: ## Run the Java tests
	./gradlew test
check-java: lint-java test-java audit-jvm ## Run the gate of Java
