
# JavaScript
#
# The section javascript of .ergon.yaml sets the options of the JavaScript targets and the steps of
# check-javascript. One run overrides an option on the command line, such as
# make test-javascript JAVASCRIPT_TEST_ARGS=test/unit.

# The options of the section javascript.
JAVASCRIPT_TEST_ARGS ?={{% with words .Options.Test.Args %}} {{% . %}}{{% end %}}

.PHONY: lint-javascript test-javascript audit-javascript check-javascript
lint: lint-javascript
test: test-javascript
check: check-javascript

lint-javascript: lint-js ## Check the JavaScript sources with Biome
test-javascript: ## Run the JavaScript tests
	npm test $(if $(JAVASCRIPT_TEST_ARGS),-- $(JAVASCRIPT_TEST_ARGS))
audit-javascript: audit-js ## Scan the packages of JavaScript for known vulnerabilities
check-javascript:{{% range .Options.Check %}} {{% . %}}-javascript{{% end %}} ## Run the gate of JavaScript
