// Copyright Dokimasia B.V. 2026
// SPDX-License-Identifier: MIT

package license_test

import (
	"io/fs"
	"os"
	"runtime"
	"testing"

	"go.dokimi.dev/assert"
	"go.dokimi.dev/assert/files"
	"go.dokimi.dev/ergon/service/license"
	"go.dokimi.dev/ergon/service/vcs"
	"go.dokimi.dev/ergon/service/vcs/vcstest"
)

// windows is the system of Windows, which has no mode that denies the owner access to a file.
const windows = "windows"

// mark is the byte-order mark of UTF-8.
var mark = string([]byte{0xef, 0xbb, 0xbf})

// TestMain runs the tests without the variables and the configuration of git of the environment,
// so git reads the working trees of the tests alone.
func TestMain(m *testing.M) {
	vcstest.Isolate()
	os.Exit(m.Run())
}

func TestHeader(t *testing.T) {
	t.Parallel()

	t.Run("Check", func(t *testing.T) {
		t.Parallel()

		t.Run("returns no finding for a header of a year, a range or a list of years", func(t *testing.T) {
			t.Parallel()
			dir := vcstest.Repository(t, files.Tree{
				"a.go": files.Text("// Copyright Dokimasia B.V. 2020\n// SPDX-License-Identifier: MIT\n\npackage a\n"),
				"b.go": files.Text(
					"// Copyright Dokimasia B.V. 2020-2026\n// SPDX-License-Identifier: MIT\n\npackage a\n",
				),
				"c.py": files.Text("# Copyright Dokimasia B.V. 2024, 2026\n# SPDX-License-Identifier: MIT\n"),
			})
			report, err := license.Check(t.Context(), dir, config())
			assert.NoError(t, err, "Check")
			assert.Equal(t, report, license.Report{Checked: 3}, "the report")
		})

		t.Run("returns the findings sorted by path", func(t *testing.T) {
			t.Parallel()
			dir := vcstest.Repository(t, files.Tree{
				"z.go": files.Text("package z\n"),
				"a/b.go": files.Text(
					"// Copyright ThesmOS B.V. 2024\n// SPDX-License-Identifier: MIT\n\npackage b\n",
				),
				"a/a.go":   files.Text("package a\n"),
				"main.css": files.Text("body {}\n"),
			})
			report, err := license.Check(t.Context(), dir, config())
			assert.NoError(t, err, "Check")
			assert.Equal(t, report.Findings, []license.Finding{
				{Path: "a/a.go", Kind: license.Missing},
				{Path: "a/b.go", Kind: license.Outdated},
				{Path: "main.css", Kind: license.Missing},
				{Path: "z.go", Kind: license.Missing},
			}, "the findings")
		})

		t.Run("skips the files without a header", func(t *testing.T) {
			t.Parallel()
			dir := vcstest.Repository(t, files.Tree{
				".gitignore": files.Text(
					"# Managed by ergon init. Add repository settings to .ergon/local/.gitignore.\nbin/\n",
				),
				"bin/tool.go":         files.Text("package main\n"),
				"gen.go":              files.Text("// Code generated by stringer. DO NOT EDIT.\n\npackage a\n"),
				"testdata/fixture.go": files.Text("package fixture\n"),
				"data.json":           files.Text("{}\n"),
				"gone.go":             files.Text("package a\n"),
			}, "gone.go")
			assert.NoError(t, os.Remove(dir+"/gone.go"), "Remove of gone.go")
			c := config()
			c.Exclude = []string{"testdata/**"}
			report, err := license.Check(t.Context(), dir, c)
			assert.NoError(t, err, "Check")
			assert.Equal(t, report, license.Report{Skipped: 5}, "the report")
		})

		t.Run("skips a link", func(t *testing.T) {
			t.Parallel()
			if runtime.GOOS == windows {
				t.Skip("Windows creates a link only for a user with the privilege to create one")
			}
			dir := vcstest.Repository(t, files.Tree{"link.go": files.Link("main.go")})
			report, err := license.Check(t.Context(), dir, config())
			assert.NoError(t, err, "Check")
			assert.Equal(t, report, license.Report{Skipped: 1}, "the report")
		})

		t.Run("returns Unsupported for a file that is not text", func(t *testing.T) {
			t.Parallel()
			dir := vcstest.Repository(t, files.Tree{"blob.go": files.Bytes([]byte{0, 1, 2, 3})})
			report, err := license.Check(t.Context(), dir, config())
			assert.NoError(t, err, "Check")
			assert.Equal(
				t,
				report.Findings,
				[]license.Finding{{Path: "blob.go", Kind: license.Unsupported}},
				"the findings",
			)
		})

		t.Run("writes nothing", func(t *testing.T) {
			t.Parallel()
			dir := vcstest.Repository(t, files.Tree{"main.go": files.Text("package main\n")})
			files.Unchanged(t, os.DirFS(dir), func() {
				_, err := license.Check(t.Context(), dir, config())
				assert.NoError(t, err, "Check")
			}, "the repository")
		})

		t.Run("returns ErrGit for a directory outside a working tree", func(t *testing.T) {
			t.Parallel()
			_, err := license.Check(t.Context(), t.TempDir(), config())
			assert.ErrorIs(t, err, vcs.ErrGit, "Check")
		})

		t.Run("returns the error of a file that does not read", func(t *testing.T) {
			t.Parallel()
			if runtime.GOOS == windows {
				t.Skip("Windows has no mode that denies the owner reading a file")
			}
			dir := vcstest.Repository(t, files.Tree{"main.go": files.Text("package main\n").WithMode(0o000)})
			_, err := license.Check(t.Context(), dir, config())
			assert.ErrorIs(t, err, fs.ErrPermission, "Check")
		})

		t.Run("returns the error of a tracked file in a directory that does not search", func(t *testing.T) {
			t.Parallel()
			if runtime.GOOS == windows {
				t.Skip("Windows has no mode that denies the owner searching a directory")
			}
			dir := vcstest.Repository(t, files.Tree{"cmd/main.go": files.Text("package main\n")}, "cmd/main.go")
			assert.NoError(t, os.Chmod(dir+"/cmd", 0o600), "Chmod of cmd")
			t.Cleanup(func() { _ = os.Chmod(dir+"/cmd", 0o755) })
			_, err := license.Check(t.Context(), dir, config())
			assert.ErrorIs(t, err, fs.ErrPermission, "Check")
		})
	})

	t.Run("Fix", func(t *testing.T) {
		t.Parallel()

		t.Run("writes the header of each file, which the check then passes", func(t *testing.T) {
			t.Parallel()
			dir := vcstest.Repository(t, files.Tree{
				"main.go":   files.Text("package main\n"),
				"run.sh":    files.Text("#!/bin/sh\necho\n"),
				"README.md": files.Text("# demo\n"),
				"old.go": files.Text(
					"// Copyright ThesmOS B.V. 2024\n// SPDX-License-Identifier: MIT\n\npackage main\n",
				),
			})
			report, err := license.Fix(t.Context(), dir, config(), 2026)
			assert.NoError(t, err, "Fix")
			assert.Equal(t, report, license.Report{
				Fixed:   []string{"README.md", "main.go", "old.go", "run.sh"},
				Checked: 4,
			}, "the report of Fix")
			again, err := license.Check(t.Context(), dir, config())
			assert.NoError(t, err, "Check")
			assert.Equal(t, again, license.Report{Checked: 4}, "the report of Check")
		})

		t.Run("leaves a file whose header matches", func(t *testing.T) {
			t.Parallel()
			dir := vcstest.Repository(t, files.Tree{"main.go": files.Text(slashes + "package main\n")})
			files.Unchanged(t, os.DirFS(dir), func() {
				report, err := license.Fix(t.Context(), dir, config(), 2027)
				assert.NoError(t, err, "Fix")
				assert.Equal(t, report, license.Report{Checked: 1}, "the report")
			}, "the repository")
		})

		t.Run("keeps the byte-order mark before the header", func(t *testing.T) {
			t.Parallel()
			dir := vcstest.Repository(t, files.Tree{"Demo.cs": files.Text(mark + "namespace Demo;\n")})
			_, err := license.Fix(t.Context(), dir, config(), 2026)
			assert.NoError(t, err, "Fix")
			files.Contains(t, os.DirFS(dir), files.Tree{
				"Demo.cs": files.Text(mark + slashes + "namespace Demo;\n"),
			}, "the fixed file")
			again, err := license.Check(t.Context(), dir, config())
			assert.NoError(t, err, "Check")
			assert.Empty(t, again.Findings, "the findings of Check")
		})

		t.Run("keeps the mode of a file", func(t *testing.T) {
			t.Parallel()
			if runtime.GOOS == windows {
				t.Skip("Windows stores no execute bit of a file")
			}
			dir := vcstest.Repository(t, files.Tree{"run.sh": files.Text("#!/bin/sh\necho\n").WithMode(0o755)})
			_, err := license.Fix(t.Context(), dir, config(), 2026)
			assert.NoError(t, err, "Fix")
			files.HasMode(t, dir+"/run.sh", 0o755, "the mode of run.sh")
		})

		t.Run("leaves a conflict and a file that is not text", func(t *testing.T) {
			t.Parallel()
			conflict := "// Copyright ThesmOS B.V. 2024\n// All rights reserved.\n\npackage main\n"
			dir := vcstest.Repository(t, files.Tree{
				"main.go": files.Text(conflict),
				"blob.go": files.Bytes([]byte{0, 1, 2, 3}),
			})
			report, err := license.Fix(t.Context(), dir, config(), 2026)
			assert.NoError(t, err, "Fix")
			assert.Equal(t, report, license.Report{
				Findings: []license.Finding{
					{Path: "blob.go", Kind: license.Unsupported},
					{Path: "main.go", Kind: license.Conflict, Line: 2},
				},
				Checked: 2,
			}, "the report")
			files.Contains(t, os.DirFS(dir), files.Tree{"main.go": files.Text(conflict)}, "the conflict")
		})

		t.Run("returns ErrGit for a directory outside a working tree", func(t *testing.T) {
			t.Parallel()
			_, err := license.Fix(t.Context(), t.TempDir(), config(), 2026)
			assert.ErrorIs(t, err, vcs.ErrGit, "Fix")
		})

		t.Run("returns the error of a file that does not write", func(t *testing.T) {
			t.Parallel()
			if runtime.GOOS == windows {
				t.Skip("the files of go.dokimi.dev/assert set no mode of a file on Windows")
			}
			dir := vcstest.Repository(t, files.Tree{"main.go": files.Text("package main\n").WithMode(0o444)})
			_, err := license.Fix(t.Context(), dir, config(), 2026)
			assert.ErrorIs(t, err, fs.ErrPermission, "Fix")
		})
	})
}
