// Code generated by the cases of errorprefix. DO NOT EDIT.

package clock

import "errors"

// ErrGenerated is an error of a generated file, which errorprefix does not read.
var ErrGenerated = errors.New("generated text")
